### ISSUE TITLE
button-tic-x01 seemingly not firing.

### ISSUE THREAD

**Issue by OpenRetroHQ** [FPGAwars/iceInputs#2]
I have a button wired to an FPGA pin that starts at 5V and goes to GND when pressed.

If i wire the button via a NOT-WIRE block then it registers the button press fine, albeit it fires on every clock cycle in my code which is undesirable (circled in green)

So i tried wiring it via a BUTTON-TIC block with the NOT parameter set to 1.. however now the button press is never registered at all. (circled in orange)

I also tried wiring the output of the NOT-WIRE into the BUTTON-TIC block leaving the BUTTON-TIC block's not parameter as its default but still doesn't register.. (circled in red)

This is probably not a bug and there is a very high chance im just using them incorrectly, but cant spot it.

<img width="617" alt="image" src="https://github.com/FPGAwars/iceInputs/assets/152508114/a14ca4d5-b685-438d-8174-baf008ae07c7">

**Comment by cavearr** [comment]
Hi! the first "test" , the "up" button,  don't work?, try to put "1"  at "pull-up" and "not" parameter.

If not work, i'll setup a button like you to try it but tell me if the "up" button works if you put "1" at the two parameters.

**Comment by OpenRetroHQ** [comment]
Ive tried every combination i can think of and cant seem to get a TIC to register when using a button with an external pullup, ill keep trying as i'm sure i'm overlooking something obvious.

Here is what the input on the fpga pin looks like as button is pressed.

<img width="1154" alt="image" src="https://github.com/FPGAwars/iceInputs/assets/152508114/95ea32f4-3401-43f0-bef4-db73a3c1210d">

**Comment by cavearr** [comment]
HI! I'm trying it with a setup of button active low (1 no press, 0 pressed).

The correct connection is this:

<img width="561" alt="Captura de pantalla 2024-03-09 a las 19 12 48" src="https://github.com/FPGAwars/iceInputs/assets/6904865/c3b57202-aadf-468d-88f9-e7f90298360b">

Only need to put 1 in "not" parameter.

I think your problem  goes from "clk" signal in your code block.

if you use a clk signal inside a block you need to syncronize all the clks, you need to put the same clk signal tu the button blocks.

Try it and tell me!

**Comment by OpenRetroHQ** [comment]
Thankyou, long story short you were correct. Really appreciated the clarification the out of sync clock wasnt on my radar.

Basically the clock i was passing in was the PLL generated clock and the clock the buttons were using was the raw external clock.

As it happened i had the PLL generated clock running at the same speed as the Crystal does so i didnt notice id wired them in differently.

Again thankyou for taking the time to respond.

**Comment by cavearr** [comment]
Don't worry! if i can help i do it! 

Thanks to you for use icestudio and give me your feedback!
